run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - typecheck

linters-settings:
  errcheck:
    # Ignore certain functions that are safe to ignore
    exclude-functions:
      - (github.com/bioharz/budget/internal/service.AuditService).LogHoldingCreate
      - (github.com/bioharz/budget/internal/service.AuditService).LogHoldingUpdate
      - (github.com/bioharz/budget/internal/service.AuditService).LogHoldingDelete

issues:
  exclude-rules:
    # Allow error checks to be ignored for certain patterns
    - linters:
        - errcheck
      text: "Error return value of .* is not checked"
      path: "_test\\.go"
    
    # Allow unused variables in test files
    - linters:
        - unused
      path: "_test\\.go"